"""
Django settings for tubdown project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

import sys
sys.stdout.reconfigure(encoding='utf-8')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m3bd*9j0r9u7ile=4wko6if3#t1o%msq%c+6yfacdrw3u-j27u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'youtube_downloader',
]

# Celery yapılandırma ayarları
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Broker URL'si (Redis örneği)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Sonuçların saklanacağı yer (Redis örneği)

CELERY_ACCEPT_CONTENT = ['json']  # Kabul edilen içerik türleri
CELERY_TASK_SERIALIZER = 'json'  # Görev verilerinin serileştirilme formatı
CELERY_RESULT_SERIALIZER = 'json'  # Görev sonuçlarının serileştirilme formatı
CELERY_TIMEZONE = 'UTC'  # Zaman dilimi ayarı (opsiyonel, UTC genellikle standarttır)

# Ekstra ayarlar (opsiyonel)
CELERY_TASK_ROUTES = {
    'myapp.tasks.add': {'queue': 'default'},  # Görevlerin yönlendirileceği kuyruklar
}
CELERY_TASK_DEFAULT_QUEUE = 'default'  # Varsayılan görev kuyruğu
CELERY_TASK_DEFAULT_EXCHANGE = 'default'  # Varsayılan görev değişimi
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'  # Varsayılan yönlendirme anahtarı




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tubdown.urls'

# settings.py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]




WSGI_APPLICATION = 'tubdown.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # Statik dosyalar için URL yolu
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Statik dosyaların toplanacağı dizin




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
